Page did not found
fe-may23-dreamTeam/product_catalog_fe pull request #1
Opened 2023-08-28 18:46 UTC by NazarBaraban

Created page with 404 error

2023-08-29 19:07 UTC, MaxSchmide approved these changes

2023-08-30 20:19 UTC, olena-ole requested changes
Looks great, but colors should correspond with tailwind config (we updated it🎉)

2023-08-31 19:03 UTC, OlhaSheliakina commented on src/pages/NotFound.tsx
> +    <main className="grid min-h-full place-items-center bg-white px-6 py-24 sm:py-32 lg:px-8">
```suggestion
    <main className="grid min-h-full place-items-center bg-white px-6 py-24 tablet:py-32 desktop:px-8">
```

2023-09-01 11:55 UTC, OlhaSheliakina approved these changes

2023-09-01 14:18 UTC, MaxSchmide approved these changes

2023-09-01 15:27 UTC, merged