Dev cart page adaptive layout
fe-may23-dreamTeam/product_catalog_fe pull request #10
Opened 2023-08-31 12:03 UTC by ihorhladkov

2023-08-31 14:34 UTC, MaxSchmide requested changes

2023-08-31 14:34 UTC, MaxSchmide commented on src/index.css
> +}
delete this

2023-08-31 14:34 UTC, MaxSchmide commented on tailwind.config.js
>        desktop: '1200px',
```suggestion
      tablet: '640px',
      desktop: '1200px',
```

2023-08-31 14:34 UTC, MaxSchmide commented on tailwind.config.js
>        desktop: '1200px',
delete unused breakpoint

2023-09-04 17:03 UTC, perfectAcedia approved these changes

2023-09-04 17:05 UTC, MaxSchmide approved these changes

2023-09-04 20:03 UTC, merged