create burger menu
fe-may23-dreamTeam/product_catalog_fe pull request #2
Opened 2023-08-29 09:26 UTC by NazarBaraban

2023-08-29 19:17 UTC, MaxSchmide requested changes

2023-08-29 19:17 UTC, MaxSchmide commented on tailwind.config.js
> +        },
you guys must discuss config customization

2023-09-02 10:44 UTC, MaxSchmide approved these changes
Good but u should delete icons from assets folder next time if u use library

2023-09-02 10:54 UTC, ihorhladkov approved these changes

2023-09-02 11:05 UTC, merged