pagination
fe-may23-dreamTeam/product_catalog_fe pull request #3
Opened 2023-08-29 17:09 UTC by olena-ole

2023-08-29 19:11 UTC, MaxSchmide commented on src/components/Pagination.tsx
> +  onPageChange,
```suggestion
  perPage,
  currentPage,
  onPageChange,
```

2023-08-29 19:14 UTC, MaxSchmide requested changes

2023-08-29 19:14 UTC, MaxSchmide commented on src/components/Pagination.tsx
> +  onPageChange,
this prop isn't optional, no sense in default value

2023-08-29 19:14 UTC, MaxSchmide commented on tailwind.config.js
> +    },
you guys must discuss about config customization

2023-08-31 10:33 UTC, NazarBaraban approved these changes

2023-08-31 10:59 UTC, MaxSchmide approved these changes
looks good

2023-08-31 11:14 UTC, merged