adding footer component
fe-may23-dreamTeam/product_catalog_fe pull request #4
Opened 2023-08-29 19:43 UTC by OlhaSheliakina

2023-08-30 20:40 UTC, olena-ole requested changes
GJ! Just make sure you compile with new config and add navigation

2023-08-30 20:40 UTC, olena-ole commented on src/components/Footer.tsx
> +        </div>
It's good to use nal with ul here, where each li has link inside

2023-08-31 10:35 UTC, NazarBaraban approved these changes

2023-09-01 12:06 UTC, ihorhladkov approved these changes

2023-09-01 17:39 UTC, merged