Phone page adaptive layout (without font)
fe-may23-dreamTeam/product_catalog_fe pull request #7
Opened 2023-08-30 14:24 UTC by ihorhladkov

2023-08-30 21:28 UTC, olena-ole submitted a review, later dismissed
GJ! Just use icons and make sure your styles correspond to the updated tailwind config

2023-08-30 21:28 UTC, olena-ole commented on src/Components/Dropdown.tsx
> +import arrowUp from '../assets/Icons/Chevron (Arrow Up).svg';
use react-icons lib ([Feather set](https://react-icons.github.io/react-icons/icons?name=fi) )

2023-08-31 15:06 UTC, MaxSchmide requested changes

2023-08-31 15:06 UTC, MaxSchmide commented on src/pages/PhonePage.tsx
> +        <div className="mb-8">
Check this divs please

2023-08-31 18:42 UTC, MaxSchmide submitted a review, later dismissed

2023-09-01 11:55 UTC, NazarBaraban submitted a review, later dismissed

2023-09-02 11:58 UTC, MaxSchmide commented
Please update with master branch

2023-09-04 12:20 UTC, olena-ole approved these changes

2023-09-04 12:24 UTC, NazarBaraban approved these changes

2023-09-04 13:21 UTC, merged